---
git-sync:
  script:
  - eval `ssh-agent`
  - echo "$PUSH_KEY" | ssh-add -
  - git sync-remote git@github.com:resource-reasoning/testing-website.git git@gitlab.doc.ic.ac.uk:resource-reasoning/testing-website.git
  - ssh-agent -k
  only:
  - triggers
