---
stages:
- test
- deploy
- "Git Sync"

test:
  stage: test
  before_script:
  - virtualenv env
  - source env/bin/activate
  script:
  - python setup.py install
  - python -m unittest discover testing
  except:
  - triggers

deploy:
  stage: deploy
  script:
  - umask 002
  - sed -e "s|%(database_uri)s|$DATABASE_URI|" production.ini.tmpl > production.ini
  - cp -r * $DEPLOY_DIR
  - cd $DEPLOY_DIR
  - virtualenv env
  - source env/bin/activate
  - python setup.py install
  - chmod -R ug+rw .
  - touch $DEPLOY_DIR/redeploy.trigger
  tags:
  - jscert-testing-website-production
  environment: production
  only:
  - production
  except:
  - triggers

git-sync:
  stage: "Git Sync"
  script:
  - eval `ssh-agent`
  - echo "$PUSH_KEY" | ssh-add -
  - git sync-remote git@github.com:resource-reasoning/testing-website.git git@gitlab.doc.ic.ac.uk:resource-reasoning/testing-website.git
  - ssh-agent -k
  only:
  - triggers
