"""Initial DB create

Revision ID: 96a91625130
Revises: 
Create Date: 2015-07-14 17:43:17.325870

"""

# revision identifiers, used by Alembic.
revision = '96a91625130'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fail_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cr1013'
    )
    op.create_table('test_cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('negative', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cr1013'
    )
    op.create_table('test_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cr1013'
    )
    op.create_table('test_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('impl_name', sa.String(), nullable=True),
    sa.Column('impl_version', sa.String(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('repo_version', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('condor_cluster', sa.SmallInteger(), nullable=True),
    sa.Column('condor_scheduler', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cr1013'
    )
    op.create_table('fail_group_memberships',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], [u'cr1013.fail_groups.id'], name='fail_group_memberships_group_id_fkey'),
    sa.ForeignKeyConstraint(['test_id'], [u'cr1013.test_cases.id'], name='fail_group_memberships_test_id_fkey'),
    sa.PrimaryKeyConstraint('group_id', 'test_id'),
    schema='cr1013'
    )
    op.create_table('test_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('system', sa.String(), nullable=True),
    sa.Column('osnodename', sa.String(), nullable=True),
    sa.Column('osrelease', sa.String(), nullable=True),
    sa.Column('osversion', sa.String(), nullable=True),
    sa.Column('hardware', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('condor_proc', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], [u'cr1013.test_jobs.id'], name='test_batches_job_id_fkey'),
    sa.PrimaryKeyConstraint('id'),
    schema='cr1013'
    )
    op.create_table('test_group_memberships',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], [u'cr1013.test_groups.id'], name='test_group_memberships_group_id_fkey'),
    sa.ForeignKeyConstraint(['test_id'], [u'cr1013.test_cases.id'], name='test_group_memberships_test_id_fkey'),
    sa.PrimaryKeyConstraint('group_id', 'test_id'),
    schema='cr1013'
    )
    op.create_table('test_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.String(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.Enum('PASS', 'FAIL', 'ABORT', 'UNKNOWN', 'TIMEOUT', name='jscert.result_text'), nullable=True),
    sa.Column('exit_code', sa.SmallInteger(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('duration', sa.Interval(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], [u'cr1013.test_batches.id'], name='test_runs_batch_id_fkey'),
    sa.ForeignKeyConstraint(['test_id'], [u'cr1013.test_cases.id'], name='test_runs_test_id_fkey'),
    sa.PrimaryKeyConstraint('id'),
    schema='cr1013'
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_runs', schema='cr1013')
    op.drop_table('test_group_memberships', schema='cr1013')
    op.drop_table('test_batches', schema='cr1013')
    op.drop_table('fail_group_memberships', schema='cr1013')
    op.drop_table('test_jobs', schema='cr1013')
    op.drop_table('test_groups', schema='cr1013')
    op.drop_table('test_cases', schema='cr1013')
    op.drop_table('fail_groups', schema='cr1013')
    ### end Alembic commands ###
